// Generated by Wrangler by running `wrangler types`

interface Env {
    ADMIN_AUTHORIZATION_TOKEN: 'ABC123'
    CLIENT_AUTHORIZATION_TOKEN: 'DEF456'
    REGION: 'auto'
    STUDIO_USER: 'admin'
    STUDIO_PASS: '123456'
    ENABLE_ALLOWLIST: 0
    ENABLE_RLS: 0
    ENABLE_CRON: 0
    ENABLE_CDC: 0
    ENABLE_INTERFACE: 0
    ENABLE_STUDIO: 0
    ENABLE_REST: 1
    ENABLE_WEBSOCKET: 1
    ENABLE_EXPORT: 1
    ENABLE_IMPORT: 1
    AUTH_ALGORITHM: 'RS256'
    AUTH_JWKS_ENDPOINT: ''
    DATABASE_DURABLE_OBJECT: DurableObjectNamespace<
        import('./src/index').StarbaseDBDurableObject
    >
}
