// Generated by Wrangler by running `wrangler types`

interface Env {
    ADMIN_AUTHORIZATION_TOKEN: 'ABC123'
    CLIENT_AUTHORIZATION_TOKEN: 'DEF456'
    REGION: 'auto'
    STUDIO_USER: 'admin'
    STUDIO_PASS: '123456'
    ENABLE_ALLOWLIST: 0
    ENABLE_RLS: 0
    AUTH_ALGORITHM: 'RS256'
    AUTH_JWKS_ENDPOINT: ''
    NEXTJS_ENV: string
    WORKER_URL: string
    DATABASE_DURABLE_OBJECT: DurableObjectNamespace<
        import('./src/index').StarbaseDBDurableObject
    >
}
