// Generated by Wrangler by running `wrangler types`

import { DurableObjectNamespace } from '@cloudflare/workers-types'
import { R2Bucket } from '@cloudflare/workers-types'

declare const __DURABLE_OBJECT_BRAND: unique symbol
export interface DurableObjectBranded {
    readonly [__DURABLE_OBJECT_BRAND]: typeof __DURABLE_OBJECT_BRAND
}

interface Env {
    ADMIN_AUTHORIZATION_TOKEN: string
    CLIENT_AUTHORIZATION_TOKEN: string
    REGION: string
    STUDIO_USER: string
    STUDIO_PASS: string
    ENABLE_ALLOWLIST: number
    ENABLE_RLS: number
    AUTH_ALGORITHM: string
    AUTH_JWKS_ENDPOINT: string
    DATABASE_DURABLE_OBJECT: DurableObjectNamespace
    BUCKET: R2Bucket
}

export interface StarbaseDBConfiguration {
    outerbaseApiKey: string
    role: 'client' | 'admin'
    features: {
        allowlist: boolean
        rls: boolean
        rest: boolean
        export: boolean
        import: boolean
    }
    BUCKET: R2Bucket
}
