#:schema node_modules/wrangler/config-schema.json
name = "starbasedb"
main = "src/index.ts"
compatibility_date = "2024-09-25"
account_id = "your-account-id"
compatibility_flags = ["nodejs_compat_v2"]

assets = { directory = "./public/" }

rules = [
  { type = "Text", globs = ["**/*.sql"], fallthrough = true }
]

# Service Bindings
## DO NOT REMOVE: TEMPLATE SERVICES ##

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

# Bind a Durable Object. Durable objects are a scale-to-zero compute primitive based on the actor model.
# Durable Objects can live for as long as needed. Use these when you need a long-running "server", such as in realtime apps.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#durable-objects
[durable_objects]
bindings = [
  { name = "DATABASE_DURABLE_OBJECT", class_name = "StarbaseDBDurableObject" }
]

# Durable Object migrations.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#migrations
[[migrations]]
tag = "v1"
new_sqlite_classes = ["StarbaseDBDurableObject"]

[vars]
# Use this in your Authorization header for full database access
ADMIN_AUTHORIZATION_TOKEN = "your-admin-token"
# Use this in your Authorization header for a user role with rules applied
CLIENT_AUTHORIZATION_TOKEN = "your-client-token"
# Deploy the Durable Object in a specific region, default is "auto"
REGION = "auto"
# Database dump configuration
CHUNK_SIZE = "1000"
EXPORT_TIMEOUT = "25000"
EXPORT_CHUNK_SIZE = "1000"
EXPORT_TIMEOUT_MS = "25000"
EXPORT_BREATHING_TIME_MS = "5000"
EXPORT_MAX_RETRIES = "3"
ENABLE_DATABASE_DUMPS = true
ENABLE_EXPORT = true

# Uncomment the section below to create a user for logging into your database UI.
# You can access the Studio UI at: https://your_endpoint/studio
# STUDIO_USER = "admin"
# STUDIO_PASS = "123456"

# Toggle to enable default features 
ENABLE_ALLOWLIST = 1
ENABLE_RLS = 1

# External database source details
# This enables Starbase to connect to an external data source
# OUTERBASE_API_KEY = ""
# EXTERNAL_DB_TYPE = "postgresql"
# EXTERNAL_DB_HOST = ""
# EXTERNAL_DB_PORT = 0
# EXTERNAL_DB_USER = ""
# EXTERNAL_DB_PASS = ""
# EXTERNAL_DB_DATABASE = ""
# EXTERNAL_DB_DEFAULT_SCHEMA = "public"

# EXTERNAL_DB_MONGODB_URI = ""
# EXTERNAL_DB_TURSO_URI = ""
# EXTERNAL_DB_TURSO_TOKEN = ""
# EXTERNAL_DB_STARBASEDB_URI = ""
# EXTERNAL_DB_STARBASEDB_TOKEN = ""
# EXTERNAL_DB_CLOUDFLARE_API_KEY = ""
# EXTERNAL_DB_CLOUDFLARE_ACCOUNT_ID = ""
# EXTERNAL_DB_CLOUDFLARE_DATABASE_ID = ""

AUTH_ALGORITHM = "RS256"
AUTH_JWKS_ENDPOINT = ""


# R2 Bucket for storing database dumps
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "database-dumps"
